### PR TITLE
new catalog version

### PR DESCRIPTION
**Pull request by riccardoklinger**
This version should work now with geopackages, pbfs and other multi-layer ogr types.

### CODE REVIEW

**Comment by lcalisto** [comment]
Cool! It works fine. I believe we should add one warning in case we don't have any layer selected because the export button only exports selected layers (and I agree that this is how it should work!). I can do that, perhaps next week I've been very busy this last 2 weeks but I should return to normality next week. Shall I accept this pull request and then I create this warning or you want to do that?

**Comment by riccardoklinger** [comment]
I am not good in writing warnings. so maybe I can address you with this issue @lcalisto ? I would also switch usage: select all found datasets by default and let the user deselect/alter the selection....

**Comment by lcalisto** [comment]
Sure I can do that! I'm not getting what you mean with the last part. _"Select all found datasets by default and let the user deselect/alter the selection"_???? Is not this that is happening now? The user needs to select the datasets in order to export them. Now he can do that, I'll keep it that way just add the warning in case none dataset is selected.

**Comment by riccardoklinger** [comment]
I want to propose to let the python code select all by default when it adds a layer to the list of found layers/datasets. Currently layers are added and user selects the ones he would like to have. 
I would switch to: Let the users deselect the ones he wouldn't like to add...

**Comment by riccardoklinger** [comment]
Do you need any additional help for this merge?

**Comment by lcalisto** [comment]
Hi sorry for my late reply. I just merged and I also added a warning in case none is selected. Now implementing issue #2 and then I'll do a new plugin release.

**Pull request merged**
