### PR TITLE
first working version

### PR DESCRIPTION
**Pull request by riccardoklinger**
This version adds a export results button, iterates over selected datasets if button is pressed, stores the extents of each layer as a feature in a polygon layer, adds the polygon layer as a memory layer to QGIS and styles it for better visualisation.

### CODE REVIEW

**Comment by lcalisto** [comment]
Thanks for the contributions. I'm kinda busy now but I will look at it as soon as I can.

**Comment by lcalisto** [comment]
After testing this commit I found that it does not work with geopackages. Can you please check? Steps to reproduce:

1 - Search a folder that has at least one geopackage and some layers intersect the collected point. I don't think it's important but I tested in a coordinate system different than 4326.
2 - Select the geopackage found 
3 - Click on Export to results

This is the error I got:

FileNotFoundError: [Errno 2] No such file or directory: '/home/user/myfolder/Geopa.gpkg (porto, Genderindex, porto poligons)' 

I tested with linux 18.04

**Comment by riccardoklinger** [comment]
yes, Found this "bug" as well. The Problem is the "layer name" which contains special chars. I will dig into it in the next days. shall I create another pull request here then?

**Comment by lcalisto** [comment]
Great! Yes perhaps its better to create another pull request dont you think? Then I just need to accept it once.

**Pull request closed without merging**
